Sync fork with upstream
remerge/go-json pull request #1
Opened 2022-07-24 08:53 UTC by itwaseasy

2022-07-25 12:28 UTC, gburanov commented
it would be best to ask @dynamix why he added these 2 commits...

@dynamix  is it performance related?

2022-08-03 18:55 UTC, dynamix requested changes
@itwaseasy - @gburanov is correct, this is performance related.

> from my point of view, disabling these features is incorrect behavior that can lead to problems.
Incorrect in what sense? There is no reason a JSON decoder has to support the `json.Unmarshaler` interface. In our case it actually leads to the a behaviour we do not want.

What effectively happens is that is that the methods generated by `easyjson` are used for the complete decoding of the OpenRTB object graph and not `go-json`. Which means we don't get any of the performance gains 😭. 

Regarding performance difference - what exactly did you benchmark? There is a major difference if you benchmark this with JSON representing a populated OpenRTB request decoded into our Go structs (Some old results here: https://github.com/remerge/ohoh-json#is-it-fast , unfortunately not yet finished https://github.com/remerge/ohoh-json)

The main reason this fork exists is for improvements targeted at the use case we have in the bidder - it isn't meant to be used generic library 😏.  

What we can do: document the behaviour and the reasoning and fix the tests after merging with upstream.

Regarding the crash: it seems the partner sends stuff following an old standard - we haven't seen any crashes in go-json in the last 18 month. I think we rather have to fix how we handle this special case.

2022-08-04 07:49 UTC, itwaseasy commented
> Incorrect in what sense? There is no reason a JSON decoder has to support the `json.Unmarshaler` interface. In our case it actually leads to the a behaviour we do not want.

In the sense that upstream declares this library as a "drop-in replacement of encoding/json", and in our case it's not. But yes, if this library is supposed to be used only in bidder, then this is understandable.

> Regarding performance difference - what exactly did you benchmark? There is a major difference if you benchmark this with JSON representing a populated OpenRTB request decoded into our Go structs (Some old results here: https://github.com/remerge/ohoh-json#is-it-fast , unfortunately not yet finished https://github.com/remerge/ohoh-json)

I used the benchmarks that are in the library.

> What we can do: document the behaviour and the reasoning and fix the tests after merging with upstream.

OK, I'll revert the changes and remove these tests because they test logic that is missed in our fork.

2022-08-04 12:33 UTC, itwaseasy commented
Well, I disabled a few thousand lines of tests because they're all based on Marshaler/Unmarshaler interface, please take a look.

2022-08-04 13:18 UTC, gburanov commented
I think if it is just tests it is fine

2022-08-04 13:18 UTC, gburanov approved these changes

2022-08-05 08:27 UTC, merged